### PR TITLE
fix: classpath containing multiple SLF4J bindings.

### PR DESCRIPTION
**Pull request by anupash**
Fixes the crash on startup of cdmi-server-1.2. Added exclusion of dependency conflicts.

`
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/CDMI/target/cdmi-server-1.2.jar!/lib/slf4j-log4j12-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/CDMI/target/cdmi-server-1.2.jar!/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (edu.kit.scc.CdmiServerApplication).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.Log4jLoggerFactory loaded from jar:file:/opt/CDMI/target/cdmi-server-1.2.jar!/lib/slf4j-log4j12-1.7.13.jar!/). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml Object of class [org.slf4j.impl.Log4jLoggerFactory] must be an instance of class ch.qos.logback.classic.LoggerContext
	at org.springframework.util.Assert.isInstanceOf(Assert.java:346)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:223)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLogger(LogbackLoggingSystem.java:215)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartedEvent(LoggingApplicationListener.java:191)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:173)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at edu.kit.scc.CdmiServerApplication.main(CdmiServerApplication.java:26)
	... 6 more
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.Log4jLoggerFactory loaded from jar:file:/opt/CDMI/target/cdmi-server-1.2.jar!/lib/slf4j-log4j12-1.7.13.jar!/). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml Object of class [org.slf4j.impl.Log4jLoggerFactory] must be an instance of class ch.qos.logback.classic.LoggerContext
	at org.springframework.util.Assert.isInstanceOf(Assert.java:346)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:223)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLogger(LogbackLoggingSystem.java:215)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartedEvent(LoggingApplicationListener.java:191)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:173)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at edu.kit.scc.CdmiServerApplication.main(CdmiServerApplication.java:26)
	... 6 more`

### CODE REVIEW

**Comment by anupash** [comment]
Here is the maven dependency tree. Please look at org.springframework.boot:spring-boot-starter-web

`
[INFO] edu.kit.scc:cdmi-server:jar:1.2
[INFO] +- edu.kit.scc:cdmi-spi:jar:0.4:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.3.2.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.3.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.3.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.3.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.3.2.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.1.3:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.13:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.13:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.16:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.3.2.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.30:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.30:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.30:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.30:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:1.3.2.RELEASE:compile
[INFO] |  |  \- org.hibernate:hibernate-validator:jar:5.2.2.Final:compile
[INFO] |  |     +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |     \- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.5:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.5:compile
[INFO] |  +- org.springframework:spring-web:jar:4.2.4.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.2.4.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-jersey:jar:1.3.2.RELEASE:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-server:jar:2.22.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.22.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.1:compile
[INFO] |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.22.1:compile
[INFO] |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.22.1:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.4.0-b31:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b31:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b31:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b31:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-locator:jar:2.4.0-b31:compile
[INFO] |  |  |  \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.22.1:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.1:compile
[INFO] |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.22.1:compile
[INFO] |  +- org.glassfish.jersey.ext:jersey-spring3:jar:2.22.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2:jar:2.4.0-b31:compile
[INFO] |  |  |  +- org.glassfish.hk2:config-types:jar:2.4.0-b31:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-core:jar:2.4.0-b31:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-config:jar:2.4.0-b31:compile
[INFO] |  |  |  |  \- org.jvnet:tiger-types:jar:1.4:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-runlevel:jar:2.4.0-b31:compile
[INFO] |  |  |  \- org.glassfish.hk2:class-model:jar:2.4.0-b31:compile
[INFO] |  |  |     \- org.glassfish.hk2.external:asm-all-repackaged:jar:2.4.0-b31:compile
[INFO] |  |  \- org.glassfish.hk2:spring-bridge:jar:2.4.0-b31:compile
[INFO] |  \- org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.22.1:compile
[INFO] |     +- org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.22.1:compile
[INFO] |     +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.6.5:compile
[INFO] |     \- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.6.5:compile
[INFO] |        \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.6.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.3.2.RELEASE:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:runtime
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  \- org.springframework:spring-test:jar:4.2.4.RELEASE:compile
[INFO] +- org.springframework:spring-core:jar:4.2.4.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-jwt:jar:1.0.3.RELEASE:compile
[INFO] |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.47:compile
[INFO] |     \- org.bouncycastle:bcprov-jdk15on:jar:1.47:compile
[INFO] +- org.springframework:spring-context:jar:4.2.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.2.4.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.2.4.RELEASE:compile
[INFO] +- org.springframework:spring-beans:jar:4.2.4.RELEASE:compile
[INFO] +- org.springframework.data:spring-data-commons:jar:1.11.2.RELEASE:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.13:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.13:compile
[INFO] +- org.springframework.boot:spring-boot-starter-redis:jar:1.3.2.RELEASE:compile
[INFO] |  +- org.springframework.data:spring-data-redis:jar:1.6.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-tx:jar:4.2.4.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context-support:jar:4.2.4.RELEASE:compile
[INFO] |  \- redis.clients:jedis:jar:2.7.3:compile
[INFO] |     \- org.apache.commons:commons-pool2:jar:2.4.2:compile
[INFO] +- com.github.kstyrc:embedded-redis:jar:0.6:compile
[INFO] |  \- com.google.guava:guava:jar:18.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:1.3.2.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:4.0.3.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-core:jar:4.0.3.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:4.0.3.RELEASE:compile
[INFO] +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] +- org.codehaus.jettison:jettison:jar:1.3.7:compile
[INFO] |  \- stax:stax-api:jar:1.0.1:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] +- commons-io:commons-io:jar:1.3.2:compile
[INFO] +- org.json:json:jar:20160810:compile
[INFO] +- com.jayway.restassured:rest-assured:jar:2.9.0:test
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.4.4:test
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:2.4.4:test
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.1:test
[INFO] |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO] |  +- com.jayway.restassured:json-path:jar:2.9.0:test
[INFO] |  |  +- org.codehaus.groovy:groovy-json:jar:2.4.4:test
[INFO] |  |  \- com.jayway.restassured:rest-assured-common:jar:2.9.0:test
[INFO] |  \- com.jayway.restassured:xml-path:jar:2.9.0:test
[INFO] |     \- org.apache.commons:commons-lang3:jar:3.3.2:test
[INFO] +- com.jayway.jsonpath:json-path:jar:2.0.0:test
[INFO] |  \- net.minidev:json-smart:jar:2.1.1:test
[INFO] |     \- net.minidev:asm:jar:1.0.2:test
[INFO] |        \- asm:asm:jar:3.3.1:test
[INFO] \- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO]    \- commons-logging:commons-logging:jar:1.0.4:compile
`

**Review by bertl4398 — APPROVED** [review]

**Comment by komputerowiec** [comment]
Hi Anupam.
Are you sure that we have to exclude slf4j in servers' pom.xml file?
I checked it, and when I use such compiled CDMI server together with my cdmi-s3-qos module then logging functionality stops working at all (however the server starts up successfully and I can interact with it with help of REST API).

**Comment by anupash** [comment]
@komputerowiec 

The logging to a file is not working working because of these warnings which are thrown after adding the exclusions.

```
log4j:WARN No appenders could be found for logger (edu.kit.scc.CdmiServerApplication). 
log4j:WARN Please initialize the log4j system properly. 
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

However, it can be solved by adding a log4j.properties to the classpath, which will correctly set the log4j environment. By default, spring uses logback classic which is causing dependency conflict with other dependencies.


```properties
#  Logging level
cdmi.log=/var/cdmi/logs/
log4j.rootLogger=INFO, file, CONSOLE

# Output to console
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %c{1}:%L - %msg%n

# Output to a log file
# Rotation with log cleanup.
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.MaxFileSize=4MB
log4j.appender.file.MaxBackupIndex=9

# Log file and format
log4j.appender.file.File=${cdmi.log}/server.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %c{1}:%L - %msg%n
```

Can you try starting the CDMI server with the command line parameter 
`-Dlog4j.configuration=file:///path/to/log4j.properties`
and see if it fixes the logging problem?

------

But apart from all of the above, were you able to reproduce the error just as me, i.e., the CDMI server would crash immediately on start because of SLF4J bindings. I was able to reproduce in 3 different machines.

------

Can you try with the latest commit? I have added a default log4j property file for proper initialisation.

**Comment by komputerowiec** [comment]
@anupash 

I see warnings when I start the server, but they are different from those on your site:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I had tried to provide log4j.properties file and `-Dlog4j.configuration=file:///path/to/log4j.properties` option (of course with rational value), but it changed nothing. I mean, the logs didn't appear.

I was not able to repeat the error that you are describing.

How do you add your module to CLASSPATH? In my testing environment I do it at compilation time. I'm simply modifying server's pom.xml to add my module to final jar:
```
<dependency>
<groupId>pl.psnc</groupId>
<artifactId>cdmi-s3-qos</artifactId>
<version>2.0.0-SNAPSHOT</version>
</dependency>
```
Apart from that, my module itself depends on `log4j-over-slf4j`

I'm not sure which commit do you mean when you write "Can you try with the latest commit?".
The most recent commit that I have found is this one:  

https://github.com/anupash/CDMI/tree/b1989736d9a6810fe5df08926ee3eaca78a3a23e
(at time when I'm writing this message, this commit is just the last commit in the master branch)

and yes I tried it.

I'm going to still study this issue. I'm replying just to provide you with the most recent state of my examination.

**Comment by anupash** [comment]
@komputerowiec 

Following this entry at Stackoverflow,

[https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder](https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinderl)

`The No-Op rollback happens only with slf4j -1.6+ so anything older than that will throw an exception and halts your deployment.`

As far as I can see from the pom of cdmi-s3-qos, I can not find an old version of slf4j.

Can you provide me the ```mvn  dependency:tree``` output?

---------

Easiest way to put your log4j.properties to class path is to put it under `src/main/resources/` directory. 

Check that you have log4j.properties in the `src/main/resources/` directory and you have recompiled the CDMI module. I have tested this commit today at our DESY deployment and tweaked the log pattern with log4j pattern layout. I can see the output in both console and a log file being created. 

Path for the log file is /var/log/cdmi-server/server.log. I tested that the log was created and was being written to.

------------

I have rebased my last commit today and added the log4j.properties file by default to the classpath.

**Comment by anupash** [comment]
@komputerowiec 

you seem to having multiple log4j entries pertaining to different versions in the pom of cdmi-s3-qos

```xml
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
			<version>1.7.13</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.21</version>
			<scope>test</scope>
		</dependency>
```

Try to have one single version. I also believe that you don't need the following.

```xml
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.12</version>
			<scope>test</scope>
		</dependency>
```

On further looking at this [log4j](https://mvnrepository.com/artifact/log4j/log4j/1.2.12) it was released in 2005.

**Comment by komputerowiec** [comment]
@anupash 
Ok, for now I have clean up my dependencies in pom file and I can see the same behavior as you.
When I use your CDMI server from your commit then logging works even if I do not provide log4j.properties file (probably because you have added one in CDMI server itself).
And, indeed when I try to use the current indigo-dc/CDMI version of server then the server crashes during start up time.

I will wait with committing my changes until your pull request will be merged with master.

BTW: I have some minor theoretical concern. Now we will end up in a position where plugins (e.g. cdmi-s3-qos and  cdmi-dcache-qos) dictate the main module (I mean the CDMI server) what low level logging library is to be used. I'm wondering if the relation shouldn't be reverse. Probably it is the server which should impose logging libraries on its plugins.

**Comment by anupash** [comment]
@komputerowiec 

If you have a look at the dependency tree after the exclusion of logback-classic, you see that spring-boot is already enforcing the dependency to be org.slf4j:log4j-over-slf4j:jar:1.7.13

On the unlikely event of cdmi plugins not using log4j-over-slf4j, this could indeed cause a problem. However, the dependency for log4j can always be explicitly added. 

If @bertl4398 agrees, I can add an explicit dependency for slf4j to the pom.

**Comment by orviz** [comment]
add to whitelist

**Comment by orviz** [comment]
retest this please

**Comment by orviz** [comment]
ok to test

**Comment by orviz** [comment]
retest this please

**Comment by orviz** [comment]
retest this please

**Comment by bertl4398** [comment]
tested and waiting for merge

**Pull request merged**
